stages:
    - deploy

docker:snapshot-container:
    image: docker:stable
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.ispirata.com
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - master@Astarte-NG/vernemq
    script:
        - docker build -t registry.ispirata.com/astarte-ng/vernemq:snapshot .
        - docker push registry.ispirata.com/astarte-ng/vernemq:snapshot
