stages:
    - deploy

variables:
    CONTAINER_SNAPSHOT_IMAGE: $DOCKER_REGISTRY/astarte-ng/vernemq:snapshot
    CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/astarte-ng/vernemq:$CI_COMMIT_TAG

docker:snapshot-container:
    image: docker:stable
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.ispirata.com
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - master@Astarte-NG/vernemq
    script:
        - docker build -t CONTAINER_SNAPSHOT_IMAGE .
        - docker push CONTAINER_SNAPSHOT_IMAGE

docker:release-container:
    image: docker:stable
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.ispirata.com
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - tags@Astarte-NG/vernemq
    script:
        - docker build -t CONTAINER_RELEASE_IMAGE .
        - docker push CONTAINER_RELEASE_IMAGE
