stages:
    - deploy

variables:
    CONTAINER_TESTING_IMAGE: $DOCKER_REGISTRY/astarte-ng/vernemq:testing
    CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/astarte-ng/vernemq:$CI_COMMIT_TAG

docker:testing-container:
    image: docker:stable
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.ispirata.com
    services:
        - docker:stable-dind
    stage: deploy
    only:
        - testing@Astarte-NG/vernemq
    script:
        - docker build -t $CONTAINER_TESTING_IMAGE .
        - docker push $CONTAINER_TESTING_IMAGE
